# Generated by Django 3.2.8 on 2021-10-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_on',
            field=models.DateTimeField(default=''),
        ),
    ]
